### ISSUE TITLE
Error in is_character(x) : object 'module_DEmiRNA' not found

### ISSUE THREAD

**Issue by bx-labs** [TreesLab/circularRNA-microRNA-mRNA-regulatory-axes-in-autism#2]
When running this R code in Rstudio: 
Step2.1_Relation_circRNA-miRNA

it showed the error message:
Error in is_character(x) : object 'module_DEmiRNA' not found

**Comment by chenchiaying** [comment]
Hi,
This R script should be fine. Make sure you input the requried data propertly, as well as the libraries.

**Comment by bx-labs** [comment]
There are only these columns in the excel sheet (circ_mi_Modules) from the input file (RNA22_circRNA_miRNA_module):
miRNAID, DEmiRNA, circ21803, circ17131, other circRNAs, etc.
There is no column as: module_DEmiRNA

**Comment by chenchiaying** [comment]
Sorry! I uploaded the old version of  RNA22_circRNA_miRNA_module.xlsx to GitHub. Now, this file is updated. Please download the new one and try it again~ Thx
